INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('GENFLIX', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('K VISION', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('NEX MEDIA', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('OKEVISION', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('ORANGE TV', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('SKYNINDO', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('TRANSVISION', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('AMEX', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('ANZ', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('BII', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('BNI', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('BUKOPIN', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('DANAMON', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('HSBC', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('MEGA', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('PANIN', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('STANDARD CHARTERED', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('BINTANG', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('BPJS', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('CAR', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('IFG LIFE', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('JIWASRAYA', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('PRUDENTIAL', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('TOKIO MARINE', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('KAI', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('MASKAPAI', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('KAPAL', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('MULTI FINANCE', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('BIMA FINANCE', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('FIF', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('HCI', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('RADANA FINANCE', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('SMART FINANCE', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('WOKA FINANCE', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('WOM', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('PDAM JAWA BARAT', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('PDAM JAWA TENGAH', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('PDAM JAWA TIMUR', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('PDAM KALIMANTAN', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('PDAM SUMATERA', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('PDAM SULAWESI & BALINUSRA', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('PGN GAS', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('INDOSAT', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('SMARTFREN', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('TELKOMSEL', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('TRI', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('XL', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('PLN', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('TELKOM', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('PBB', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('PKB', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('ZAKAT', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('MTIX', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('TIXID', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('DANA', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('GOJEK', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('GOJEK DRIVER', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('GRAB DRIVER', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('LINKAJA', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('OVO', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('SHOPEEPAY', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('SPEEDCASH', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('BRIZZI', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('MANDIRI', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('AERIA GAMES', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('ARENA OF VALOR (AOV)', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('BATTLENET', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('CALL OF DUTY', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('CALL OF DUTY: MOBILE', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('CHERRY CREDITS', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('FREE FIRE', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('GARENA', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('GEMSCOOL', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('GOCASH GAME CARD', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('GOOGLE PLAY', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('HAGO', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('HIGGS DOMINO', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('ITUNES', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('LIFEAFTER', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('LOKAPALA', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('LYTO', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('MARVEL SUPER WARS', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('MEGAXUS', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('MMOG.ASIA', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('MOBILE LEGENDS', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('MOGCAZ', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('MOGPLAY', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('NCSOFT', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('PUBG', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('RAGNAROK ETERNAL LOVE', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('RAZER', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('RIDE OUT HEROES', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('STEAM', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('UNIPIN', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('WAVE', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('WORLD OF TANKS', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('WORLD OF WARSHIPS', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('ZEPETTO', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('AXIS', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('ALFAMART', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('AMAZON', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('CAREFOUR', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('GRAMEDIA', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('INDOMARET', NOW(), NOW());
INSERT INTO rb_groups (name, created_at, updated_at) VALUES ('SKYPE', NOW(), NOW());
