INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('bills', 'TV KABEL', 'GENFLIX', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('bills', 'TV KABEL', 'K VISION', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('bills', 'TV KABEL', 'NEX MEDIA', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('bills', 'TV KABEL', 'OKEVISION', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('bills', 'TV KABEL', 'ORANGE TV', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('bills', 'TV KABEL', 'SKYNINDO', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('bills', 'TV KABEL', 'TRANSVISION', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('bills', 'KARTU KREDIT', 'AMEX', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('bills', 'KARTU KREDIT', 'ANZ', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('bills', 'KARTU KREDIT', 'BII', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('bills', 'KARTU KREDIT', 'BNI', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('bills', 'KARTU KREDIT', 'BUKOPIN', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('bills', 'KARTU KREDIT', 'DANAMON', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('bills', 'KARTU KREDIT', 'HSBC', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('bills', 'KARTU KREDIT', 'MEGA', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('bills', 'KARTU KREDIT', 'PANIN', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('bills', 'KARTU KREDIT', 'STANDARD CHARTERED', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('bills', 'ASURANSI', 'BINTANG', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('bills', 'ASURANSI', 'BPJS', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('bills', 'ASURANSI', 'CAR', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('bills', 'ASURANSI', 'IFG LIFE', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('bills', 'ASURANSI', 'JIWASRAYA', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('bills', 'ASURANSI', 'PRUDENTIAL', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('bills', 'ASURANSI', 'TOKIO MARINE', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('bills', 'TIKET', 'KAI', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('bills', 'TIKET', 'MASKAPAI', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('bills', 'TIKET', 'KAPAL', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('bills', 'MULTI FINANCE', 'MULTI FINANCE', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('bills', 'MULTI FINANCE', 'BIMA FINANCE', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('bills', 'MULTI FINANCE', 'FIF', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('bills', 'MULTI FINANCE', 'HCI', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('bills', 'MULTI FINANCE', 'RADANA FINANCE', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('bills', 'MULTI FINANCE', 'SMART FINANCE', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('bills', 'MULTI FINANCE', 'WOKA FINANCE', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('bills', 'MULTI FINANCE', 'WOM', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('bills', 'PDAM', 'PDAM JAWA BARAT', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('bills', 'PDAM', 'PDAM JAWA TENGAH', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('bills', 'PDAM', 'PDAM JAWA TIMUR', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('bills', 'PDAM', 'PDAM KALIMANTAN', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('bills', 'PDAM', 'PDAM SUMATERA', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('bills', 'PDAM', 'PDAM SULAWESI & BALINUSRA', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('bills', 'GAS ALAM', 'PGN GAS', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('bills', 'HP PASCABAYAR', 'INDOSAT', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('bills', 'HP PASCABAYAR', 'SMARTFREN', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('bills', 'HP PASCABAYAR', 'TELKOMSEL', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('bills', 'HP PASCABAYAR', 'TRI', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('bills', 'HP PASCABAYAR', 'XL', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('bills', 'PLN', 'PLN', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('bills', 'TELKOM', 'TELKOM', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('public', 'PAJAK', 'PBB', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('public', 'PAJAK', 'PKB', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('public', 'ZAKAT', 'ZAKAT', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'BIOSKOP', 'MTIX', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'BIOSKOP', 'TIXID', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'E-MONEY', 'DANA', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'E-MONEY', 'GOJEK', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'E-MONEY', 'GOJEK DRIVER', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'E-MONEY', 'GRAB DRIVER', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'E-MONEY', 'LINKAJA', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'E-MONEY', 'OVO', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'E-MONEY', 'SHOPEEPAY', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'E-MONEY', 'SPEEDCASH', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'E-TOLL', 'BRIZZI', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'E-TOLL', 'MANDIRI', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'GAME', 'AERIA GAMES', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'GAME', 'ARENA OF VALOR (AOV)', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'GAME', 'BATTLENET', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'GAME', 'CALL OF DUTY', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'GAME', 'CALL OF DUTY: MOBILE', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'GAME', 'CHERRY CREDITS', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'GAME', 'FREE FIRE', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'GAME', 'GARENA', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'GAME', 'GEMSCOOL', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'GAME', 'GOCASH GAME CARD', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'GAME', 'GOOGLE PLAY', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'GAME', 'HAGO', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'GAME', 'HIGGS DOMINO', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'GAME', 'ITUNES', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'GAME', 'LIFEAFTER', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'GAME', 'LOKAPALA', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'GAME', 'LYTO', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'GAME', 'MARVEL SUPER WARS', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'GAME', 'MEGAXUS', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'GAME', 'MMOG.ASIA', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'GAME', 'MOBILE LEGENDS', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'GAME', 'MOGCAZ', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'GAME', 'MOGPLAY', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'GAME', 'NCSOFT', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'GAME', 'PUBG', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'GAME', 'RAGNAROK ETERNAL LOVE', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'GAME', 'RAZER', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'GAME', 'RIDE OUT HEROES', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'GAME', 'STEAM', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'GAME', 'UNIPIN', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'GAME', 'WAVE', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'GAME', 'WORLD OF TANKS', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'GAME', 'WORLD OF WARSHIPS', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'GAME', 'ZEPETTO', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'PAKET DATA', 'AXIS', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'BELANJA', 'ALFAMART', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'BELANJA', 'AMAZON', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'BELANJA', 'CAREFOUR', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'BELANJA', 'GRAMEDIA', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'BELANJA', 'INDOMARET', NOW(), NOW());
INSERT INTO rb_groups (type, subtype, name, created_at, updated_at) VALUES ('topup', 'BELANJA', 'SKYPE', NOW(), NOW());