<?php

namespace Kevinpurwito\LaravelRajabiller\Tests;

use Kevinpurwito\LaravelRajabiller\RajabillerServiceProvider;

class TestCase extends \Orchestra\Testbench\TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function getPackageProviders($app)
    {
        return [
            RajabillerServiceProvider::class,
        ];
    }

    public function getEnvironmentSetUp($app)
    {
        // New Dotenv
        if (file_exists(dirname(__DIR__) . '/.env')) {
            (\Dotenv\Dotenv::createImmutable(dirname(__DIR__), '.env'))->load();
        }
    }
}
